# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 112168b5b36741532e5409ee0ace5a6306f6e79616eb954d3020654be3d3ccc716a5d7279eb69fa6c75dc5290e69747e5651390186bc60de0ed36fff1dcc66a0

test:
  secret_key_base: d0274fec49badd9ef2036aa7567b7f748a4e3beff16a2fbb44a117bcf0f26faff6a349a5c12d942944c03d535b5e9c9e42bcec4d3fb26c0ad282404e79cf95d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
