# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5ac15998fa15dd531b8b489d2296d616de56052af310174dc6c36faf97b8e6062dafe31edb83a72163dec9fa890c37863375e5066437a08cf24ab3149ee733e

test:
  secret_key_base: a2e5db104f8dd22e54ec5639da8dde4d2c5aca8d8324cf639ff3f82f24d1f92643524de0e98ca79ba5f41dd99efd53f3984a5ebf7dacc73016f8df345100e9dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
