# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71b086da6925b8faaa92c558b04f9509b47bdc2190b32e8dfe594403280d5393754911914c1fc132dbb8e6f0fb7e4e56d4bb4596ccbd80cf5113c4ef84da82d4

test:
  secret_key_base: 777e79b3d652b57d8477cdd6b4643c08344758cb57854fd90854ec36307a4a2d05fcf634e9ceb842db2b40ca3983440cd98f3b6f763d997dd9b05d906d1c3d50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
